name: Finished Release
on:
  milestone:
    types: [closed]
jobs:
  build:
    name: finish the release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Run package
        id: chart_informations
        uses: nolte/github-action/helm/set_facts@feature/shasum

      - uses: actions/setup-python@v1
      - name: set PY
        run: echo "::set-env name=PY::$(python --version --version | sha256sum | cut -d' ' -f1)"

      - name: set release version
        uses: nolte/github-action/utils/bump2version@feature/shasum
        with:
          currentVersion: "${{ steps.chart_informations.outputs.CHARTVERSION }}"
          part: release

      - name: load relase chart informations
        id: chart_informations_release
        uses: nolte/github-action/helm/set_facts@feature/shasum

      - name: Commit files
        run: |
          git commit -m "Update to Release Version ${{ steps.chart_informations_release.outputs.CHARTVERSION }} close Milestone ${{ github.event.milestone.title }}" -a
          git checkout -b release/rc-${{ steps.chart_informations_release.outputs.CHARTVERSION }}
          git checkout develop

      - name: update to next develop version
        uses: nolte/github-action/utils/bump2version@feature/shasum
        with:
          currentVersion: "${{ steps.chart_informations_release.outputs.CHARTVERSION }}"
          part: minor

      - name: load relase chart next develop version
        id: chart_informations_next_dev
        uses: nolte/github-action/helm/set_facts@feature/shasum

      - name: Commit files
        run: |
          git commit -m "Update to next Develop Version ${{ steps.chart_informations_next_dev.outputs.CHARTVERSION }}" -a
          git push --all origin

      - name: Initialize Pull Request
        uses: nolte/github-action/utils/pullrequest@feature/shasum
        id: pull_request_release_master
        with:
          pull_request_token: ${{ secrets.GITHUB_TOKEN }}
          head: release/rc-${{ steps.chart_informations_release.outputs.CHARTVERSION }}
          base: master
          title: 'Update master to Latest Release ${{ steps.chart_informations_release.outputs.CHARTVERSION }}'
          mileStoneNumber: "${{ github.event.milestone.number }}"
          labels: "automerge, release"
          body: >
            This Pull for update the Presentation Master Branch.

      - name: accept the pull request
        uses: sudo-bot/action-pull-request-merge@v1.0.3
        with:
            args: "--trace"
            github-token: ${{ secrets.GITHUB_TOKEN }}
            number: ${{ steps.pull_request_release_master.outputs.pullRequestNumber }}
            merge-method: merge
            filter-label: automerge
  release:
    name: finish the release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Run package
        uses: nolte/github-action/helm/build@master

      - name: Echo the greeting's time
        run: sudo chmod 777 -R ./dist

      - name: Run shasum
        uses: nolte/github-action/utils/sha256sum@feature/shasum

      - name: Create Release Notes
        uses: docker://decathlon/release-notes-generator-action:2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_FOLDER: dist
          USE_MILESTONE_TITLE: "true"

      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          path: "dist"
          name: "dist"      