name: Milestone Management
on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  pulllabeld:
    name: Add Milestone to Pull Request
    runs-on: ubuntu-latest
    env:
      GOARCH: amd64
      GOOS: linux
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: develop

      - name: read release informations
        id: chart_informations
        uses: nolte/github-action/helm/set_facts@feature/shasum


      - uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |

            const { data: milestones } = await github.issues.listMilestonesForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open"
            })
            console.log(milestones)
            github.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.pull_request.number,
              milestone: milestones[0].number
            })
